ethereum_package = import_module("github.com/ethpandaops/ethereum-package/main.star")

# Brings up the whole harness topology in a single enclave:
#   1. the Arkiv chain  — arkiv-node EL + lighthouse CL, with genesis / JWT /
#      validators generated by ethereum-package
#   2. the base chain   — a bespoke plain-reth --dev node that sits below the
#      Arkiv chain as the DA / settlement substrate (the committer posts here
#      later). Plain reth, no Arkiv semantics, no CL (--dev auto-mines).


def run(plan, args):
    ethereum_package.run(plan, args["ethereum_package"])

    base = args.get("base_chain", {})
    plan.add_service(
        name = "base-chain",
        config = ServiceConfig(
            image = base.get("image", "ghcr.io/paradigmxyz/reth:v2.2.0"),
            ports = {
                "rpc": PortSpec(
                    number = 8545,
                    transport_protocol = "TCP",
                    application_protocol = "http",
                ),
            },
            cmd = [
                "node",
                "--dev",
                "--dev.block-time", base.get("block_time", "2s"),
                "--http",
                "--http.addr", "0.0.0.0",
                "--http.api", "eth,net,web3,txpool",
            ],
        ),
    )
